<?php

namespace AppBundle\Repository;

/**
 * NurlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurlRepository extends \Doctrine\ORM\EntityRepository
{
}
