<?php

namespace AppBundle\Repository;

/**
 * PendingNurlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingNurlRepository extends \Doctrine\ORM\EntityRepository
{
}
