<?php

namespace AppBundle\Repository;

/**
 * ProposedTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposedTagsRepository extends \Doctrine\ORM\EntityRepository
{
}
