<?php

namespace AppBundle\Repository;

/**
 * ReportedNurlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportedNurlRepository extends \Doctrine\ORM\EntityRepository
{
}
