<?php

namespace AppBundle\Repository;

/**
 * UserBanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBanRepository extends \Doctrine\ORM\EntityRepository
{
}
